name: 'Check Local Swift Dependencies'
description: 'This Bash script checks if any Package.swift files in a Git repository contain local Swift package references'

runs:
  using: 'composite'
  steps:
    - name: run script
      shell: bash
      run: |
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then  # if OS is linux
          git config --global --add safe.directory $PWD
        fi
        chmod -R oug+x ${GITHUB_ACTION_PATH}/check-local-swift-dependencies.sh
        ${GITHUB_ACTION_PATH}/check-local-swift-dependencies.sh

branding:
  icon: 'server'
  color: 'green'